/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin': RouteRecordInfo<'admin', '/admin', Record<never, never>, Record<never, never>>,
    'admin-reports': RouteRecordInfo<'admin-reports', '/AdminReports', Record<never, never>, Record<never, never>>,
    'admin-users': RouteRecordInfo<'admin-users', '/AdminUsers', Record<never, never>, Record<never, never>>,
    'business': RouteRecordInfo<'business', '/business', Record<never, never>, Record<never, never>>,
    'business-activity-times': RouteRecordInfo<'business-activity-times', '/BusinessActivityTimes', Record<never, never>, Record<never, never>>,
    'business-analytics': RouteRecordInfo<'business-analytics', '/BusinessAnalytics', Record<never, never>, Record<never, never>>,
    'business-appointments-calendar': RouteRecordInfo<'business-appointments-calendar', '/BusinessAppointmentsCalendar', Record<never, never>, Record<never, never>>,
    'business-appointments-settings': RouteRecordInfo<'business-appointments-settings', '/BusinessAppointmentsSettings', Record<never, never>, Record<never, never>>,
    'business-connect': RouteRecordInfo<'business-connect', '/BusinessConnect', Record<never, never>, Record<never, never>>,
    'business-customers-list': RouteRecordInfo<'business-customers-list', '/BusinessCustomersList', Record<never, never>, Record<never, never>>,
    'business-marketing-qr': RouteRecordInfo<'business-marketing-qr', '/BusinessMarketingQR', Record<never, never>, Record<never, never>>,
    'business-marketing-reminders': RouteRecordInfo<'business-marketing-reminders', '/BusinessMarketingReminders', Record<never, never>, Record<never, never>>,
    'business-marketing-sms': RouteRecordInfo<'business-marketing-sms', '/BusinessMarketingSMS', Record<never, never>, Record<never, never>>,
    'business-online-booking': RouteRecordInfo<'business-online-booking', '/BusinessOnlineBooking', Record<never, never>, Record<never, never>>,
    'business-orders': RouteRecordInfo<'business-orders', '/BusinessOrders', Record<never, never>, Record<never, never>>,
    'business-plan-invoices': RouteRecordInfo<'business-plan-invoices', '/BusinessPlanInvoices', Record<never, never>, Record<never, never>>,
    'business-plan-monthly': RouteRecordInfo<'business-plan-monthly', '/BusinessPlanMonthly', Record<never, never>, Record<never, never>>,
    'business-services-offered': RouteRecordInfo<'business-services-offered', '/BusinessServicesOffered', Record<never, never>, Record<never, never>>,
    'business-support-chat': RouteRecordInfo<'business-support-chat', '/BusinessSupportChat', Record<never, never>, Record<never, never>>,
    'business-support-whatsapp': RouteRecordInfo<'business-support-whatsapp', '/BusinessSupportWhatsapp', Record<never, never>, Record<never, never>>,
    'business-team-availability': RouteRecordInfo<'business-team-availability', '/BusinessTeamAvailability', Record<never, never>, Record<never, never>>,
    'business-team-members': RouteRecordInfo<'business-team-members', '/BusinessTeamMembers', Record<never, never>, Record<never, never>>,
    'business-top-customers': RouteRecordInfo<'business-top-customers', '/BusinessTopCustomers', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
  }
}
