/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin': RouteRecordInfo<'admin', '/admin', Record<never, never>, Record<never, never>>,
    'admin-reports': RouteRecordInfo<'admin-reports', '/AdminReports', Record<never, never>, Record<never, never>>,
    'admin-users': RouteRecordInfo<'admin-users', '/AdminUsers', Record<never, never>, Record<never, never>>,
    'business': RouteRecordInfo<'business', '/business', Record<never, never>, Record<never, never>>,
    'business-activity-times': RouteRecordInfo<'business-activity-times', '/BusinessActivityTimes', Record<never, never>, Record<never, never>>,
    'business-analytics': RouteRecordInfo<'business-analytics', '/BusinessAnalytics', Record<never, never>, Record<never, never>>,
    'business-appointments-calendar': RouteRecordInfo<'business-appointments-calendar', '/BusinessAppointmentsCalendar', Record<never, never>, Record<never, never>>,
    'business-appointments-settings': RouteRecordInfo<'business-appointments-settings', '/BusinessAppointmentsSettings', Record<never, never>, Record<never, never>>,
    'business-chat': RouteRecordInfo<'business-chat', '/BusinessChat', Record<never, never>, Record<never, never>>,
    'business-connect': RouteRecordInfo<'business-connect', '/BusinessConnect', Record<never, never>, Record<never, never>>,
    'business-customers-list': RouteRecordInfo<'business-customers-list', '/BusinessCustomersList', Record<never, never>, Record<never, never>>,
    'business-marketing-qr': RouteRecordInfo<'business-marketing-qr', '/BusinessMarketingQR', Record<never, never>, Record<never, never>>,
    'business-marketing-reminders': RouteRecordInfo<'business-marketing-reminders', '/BusinessMarketingReminders', Record<never, never>, Record<never, never>>,
    'business-marketing-sms': RouteRecordInfo<'business-marketing-sms', '/BusinessMarketingSMS', Record<never, never>, Record<never, never>>,
    'business-online-booking': RouteRecordInfo<'business-online-booking', '/BusinessOnlineBooking', Record<never, never>, Record<never, never>>,
    'business-orders': RouteRecordInfo<'business-orders', '/BusinessOrders', Record<never, never>, Record<never, never>>,
    'business-plan-invoices': RouteRecordInfo<'business-plan-invoices', '/BusinessPlanInvoices', Record<never, never>, Record<never, never>>,
    'business-plan-monthly': RouteRecordInfo<'business-plan-monthly', '/BusinessPlanMonthly', Record<never, never>, Record<never, never>>,
    'business-services-offered': RouteRecordInfo<'business-services-offered', '/BusinessServicesOffered', Record<never, never>, Record<never, never>>,
    'business-support-chat': RouteRecordInfo<'business-support-chat', '/BusinessSupportChat', Record<never, never>, Record<never, never>>,
    'business-support-whatsapp': RouteRecordInfo<'business-support-whatsapp', '/BusinessSupportWhatsapp', Record<never, never>, Record<never, never>>,
    'business-team-availability': RouteRecordInfo<'business-team-availability', '/BusinessTeamAvailability', Record<never, never>, Record<never, never>>,
    'business-team-members': RouteRecordInfo<'business-team-members', '/BusinessTeamMembers', Record<never, never>, Record<never, never>>,
    'business-top-customers': RouteRecordInfo<'business-top-customers', '/BusinessTopCustomers', Record<never, never>, Record<never, never>>,
    'chat': RouteRecordInfo<'chat', '/chat', Record<never, never>, Record<never, never>>,
    'forms-autocomplete': RouteRecordInfo<'forms-autocomplete', '/forms/autocomplete', Record<never, never>, Record<never, never>>,
    'forms-checkbox': RouteRecordInfo<'forms-checkbox', '/forms/checkbox', Record<never, never>, Record<never, never>>,
    'forms-combobox': RouteRecordInfo<'forms-combobox', '/forms/combobox', Record<never, never>, Record<never, never>>,
    'forms-custom-input': RouteRecordInfo<'forms-custom-input', '/forms/custom-input', Record<never, never>, Record<never, never>>,
    'forms-date-time-picker': RouteRecordInfo<'forms-date-time-picker', '/forms/date-time-picker', Record<never, never>, Record<never, never>>,
    'forms-editors': RouteRecordInfo<'forms-editors', '/forms/editors', Record<never, never>, Record<never, never>>,
    'forms-file-input': RouteRecordInfo<'forms-file-input', '/forms/file-input', Record<never, never>, Record<never, never>>,
    'forms-form-layouts': RouteRecordInfo<'forms-form-layouts', '/forms/form-layouts', Record<never, never>, Record<never, never>>,
    'forms-form-validation': RouteRecordInfo<'forms-form-validation', '/forms/form-validation', Record<never, never>, Record<never, never>>,
    'forms-form-wizard-icons': RouteRecordInfo<'forms-form-wizard-icons', '/forms/form-wizard-icons', Record<never, never>, Record<never, never>>,
    'forms-form-wizard-numbered': RouteRecordInfo<'forms-form-wizard-numbered', '/forms/form-wizard-numbered', Record<never, never>, Record<never, never>>,
    'forms-radio': RouteRecordInfo<'forms-radio', '/forms/radio', Record<never, never>, Record<never, never>>,
    'forms-range-slider': RouteRecordInfo<'forms-range-slider', '/forms/range-slider', Record<never, never>, Record<never, never>>,
    'forms-rating': RouteRecordInfo<'forms-rating', '/forms/rating', Record<never, never>, Record<never, never>>,
    'forms-select': RouteRecordInfo<'forms-select', '/forms/select', Record<never, never>, Record<never, never>>,
    'forms-slider': RouteRecordInfo<'forms-slider', '/forms/slider', Record<never, never>, Record<never, never>>,
    'forms-switch': RouteRecordInfo<'forms-switch', '/forms/switch', Record<never, never>, Record<never, never>>,
    'forms-textarea': RouteRecordInfo<'forms-textarea', '/forms/textarea', Record<never, never>, Record<never, never>>,
    'forms-textfield': RouteRecordInfo<'forms-textfield', '/forms/textfield', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'tables-simple-table': RouteRecordInfo<'tables-simple-table', '/tables/simple-table', Record<never, never>, Record<never, never>>,
  }
}
